In [1]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/Datamanim/datarepo/main/adp/24/problem2.csv',encoding = 'cp949')
df

    광고횟수 광고비  매출액
0      2  낮음   15
1      3  낮음   16
2      4  낮음   17
3      4  높음   18
4      5  높음   20
5      6  높음   22
6      7  낮음   24
7      9  높음   26
8     11  높음   28
9     12  낮음   29
10    13  높음   31

# 1. 광고비 변수를 가변수 처리후 다중회귀를 수행하여 회귀계수가 유의한지 검정하시오.

In [2]:
# 범주형 변수인 광고비를 get_dummies로 더미코딩 하는 전처리를 진행하였다. 
# 범주의 수준보다 1개의 개수가 적은 가변수를 생성함으로써 다중공선성을 피할 수 있다.
df2 = pd.get_dummies(df, columns = ['광고비'], drop_first = True)
df2

    광고횟수  매출액  광고비_높음
0      2   15       0
1      3   16       0
2      4   17       0
3      4   18       1
4      5   20       1
5      6   22       1
6      7   24       0
7      9   26       1
8     11   28       1
9     12   29       0
10    13   31       1

In [3]:
'''
회귀계수의 유의성을 위해 회귀계수가 0인지 0이 아닌지에 대해 t-검정을 실시한다. 
t-검정에 대한 귀무가설은 회귀계수는 0과 차이가 없다이고, 대립가설은 회귀계수가 0과 차이가 있다. 즉, 
회귀계수가 통계적으로 유의하다이다.

statsmodels를 통해 아래와 같이 각 회귀계수를 구하고, t-검정을 실시한 결과를 구하였다.
광고횟수의 회귀계수는 1.4350, t 통계량은 19.518이며 이 때 p-val는 0.000을 나타낸다.
유의수준 보다 p-value가 작기 때문에 귀무가설을 기각하고 대립가설을 채택한다. 즉, 광고횟수의 회귀계수는 통계적으로 유의하다.
광고비의 회귀계수 0.5227이고, t통계량은 0.975이며 p-value는 0.358이다. p-value가 유의수준보다 크기 때문에 귀무가설을 기각할 수 없으며 해당 회귀계수는 통계적으로 유의하다고 볼 수 없다
'''

import statsmodels.api as sm
X = df2[['광고횟수', '광고비_높음']]
y = df2['매출액']
X_ = sm.add_constant(X)
model = sm.OLS(y,X_)
fitted = model.fit()
fitted.summary()

C:\Users\235ju\anaconda3\lib\site-packages\scipy\stats\_stats_py.py:1769: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=11
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                    매출액   R-squared:                       0.982
Model:                            OLS   Adj. R-squared:                  0.978
Method:                 Least Squares   F-statistic:                     221.2
Date:                Wed, 30 Aug 2023   Prob (F-statistic):           9.96e-08
Time:                        11:02:11   Log-Likelihood:                -11.883
No. Observations:                  11   AIC:                             29.77
Df Residuals:                       8   BIC:                             30.96
Df Model:                           2
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const         12.1641      0.556     21.876      0.000      10.882      13.446
광고횟수           1.4350      0.074     19.518      0.000       1.265       1.605
광고비_높음         0.5227      0.536      0.975      0.358      -0.713       1.759
==============================================================================
Omnibus:                        7.665   Durbin-Watson:                   0.919
Prob(Omnibus):                  0.022   Jarque-Bera (JB):                3.407
Skew:                           1.265   Prob(JB):                        0.182
Kurtosis:                       4.015   Cond. No.                         18.9
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

# 회귀식이 유의한지 판단하시오.

* 회귀식의 유의성은 다중회귀 모델의 F 통계량을 통해 판단한다. 앞에서 얻은 F통계량은 221.2이고, 그 p-value는 유의수준인 0.05보다 작다. 이를 근거로 해당 회귀식은 통계적으로 유의하다고 할 수 있다.

# 모델의 설명력(예측 정확도)은 어떤가?

* 모델의 설명력은 수정된 R^2으로 알 수 있다. 수정된 R^2의 범위는 0~1까지이며, 모형의 예측 정확도가 높아지면 결정계수가 1에 가까워짐을 알 수 있다. 
* 현재 모델의 수정된 R^2을 살펴보면 0.978로 상당히 높은 설명력을 가지고 있다고 할 수 있다