# 과제 2
    데이터 : "7.세종시_아파트(전월세)_실거래가.csv"
    1) 세종시 데이터에서 컬럼 확인 후, unnamed 컬럼 제거
    2) 전월세구분 컬럼에서 unique값 확인  
    3) index= 100~200, column = 전월세구분, 전용면적(㎡),보증금(만원)으로 이루어진 데이터프레임 추출 
    4) 0~200 index를 가진 행 삭제 
    5) 건축년도 컬럼 중복 제거 결과 출력

In [2]:
import pandas as pd
df = pd.read_csv('./data/7.세종시_아파트(전월세)_실거래가.csv')
df

,Unnamed: 0,계약년월,계약일,시군구,본번,부번,단지명,전월세구분,전용면적(㎡),보증금(만원),월세(만원),층,건축년도
0,0,201701,13,세종특별자치시 고운동,1396,0,가락마을 20단지(호반베르디움5차),전세,84.9895,10000,0,13,2015
1,1,201701,14,세종특별자치시 고운동,1396,0,가락마을 20단지(호반베르디움5차),전세,84.9895,18000,0,19,2015
2,2,201701,14,세종특별자치시 고운동,1396,0,가락마을 20단지(호반베르디움5차),전세,59.8338,17000,0,10,2015
3,3,201701,15,세종특별자치시 고운동,1396,0,가락마을 20단지(호반베르디움5차),전세,84.9895,17000,0,2,2015
4,4,201702,4,세종특별자치시 고운동,1396,0,가락마을 20단지(호반베르디움5차),월세,84.9895,10000,30,13,2015
...,...,...,...,...,...,...,...,...,...,...,...,...,...
38890,38890,202011,21,세종특별자치시 해밀동,6402,1,해밀마을 2단지,월세,102.8300,10000,100,5,2020
38891,38891,202012,8,세종특별자치시 해밀동,6402,1,해밀마을 2단지,월세,102.5300,10000,95,14,2020
38892,38892,202012,11,세종특별자치시 해밀동,6402,1,해밀마을 2단지,전세,84.9500,30000,0,18,2020
38893,38893,202012,12,세종특별자치시 해밀동,6402,1,해밀마을 2단지,전세,84.9500,34000,0,18,2020
38894,38894,202012,13,세종특별자치시 해밀동,6402,1,해밀마을 2단지,월세,84.9500,8000,85,16,2020

In [7]:
#1) 세종시 데이터에서 컬럼 확인 후, unnamed 컬럼 제거
df.drop(columns = 'Unnamed: 0',inplace = True)
df

,계약년월,계약일,시군구,본번,부번,단지명,전월세구분,전용면적(㎡),보증금(만원),월세(만원),층,건축년도
0,201701,13,세종특별자치시 고운동,1396,0,가락마을 20단지(호반베르디움5차),전세,84.9895,10000,0,13,2015
1,201701,14,세종특별자치시 고운동,1396,0,가락마을 20단지(호반베르디움5차),전세,84.9895,18000,0,19,2015
2,201701,14,세종특별자치시 고운동,1396,0,가락마을 20단지(호반베르디움5차),전세,59.8338,17000,0,10,2015
3,201701,15,세종특별자치시 고운동,1396,0,가락마을 20단지(호반베르디움5차),전세,84.9895,17000,0,2,2015
4,201702,4,세종특별자치시 고운동,1396,0,가락마을 20단지(호반베르디움5차),월세,84.9895,10000,30,13,2015
...,...,...,...,...,...,...,...,...,...,...,...,...
38890,202011,21,세종특별자치시 해밀동,6402,1,해밀마을 2단지,월세,102.8300,10000,100,5,2020
38891,202012,8,세종특별자치시 해밀동,6402,1,해밀마을 2단지,월세,102.5300,10000,95,14,2020
38892,202012,11,세종특별자치시 해밀동,6402,1,해밀마을 2단지,전세,84.9500,30000,0,18,2020
38893,202012,12,세종특별자치시 해밀동,6402,1,해밀마을 2단지,전세,84.9500,34000,0,18,2020
38894,202012,13,세종특별자치시 해밀동,6402,1,해밀마을 2단지,월세,84.9500,8000,85,16,2020

In [8]:
#2) 전월세구분 컬럼에서 unique값 확인  
df['전월세구분'].unique()

array(['전세', '월세'], dtype=object)

In [14]:
#3) index= 100~200, column = 전월세구분, 전용면적(㎡),보증금(만원)으로 이루어진 데이터프레임 추출
df.loc[100:200,['전월세구분','전용면적(㎡)','보증금(만원)']]

    전월세구분  전용면적(㎡)  보증금(만원)
100    전세  73.7130    13000
101    월세  73.7130     1200
102    전세  84.9837    15000
103    전세  73.7130    11000
104    전세  73.7130    10000
..    ...      ...      ...
196    전세  59.9917     8000
197    전세  59.9917    11000
198    월세  84.9894     1000
199    전세  84.9894    15000
200    전세  59.9917    12000

[101 rows x 3 columns]

In [23]:
###4) 0~200 index를 가진 행 삭제 
df.drop(df.index[0:201])

,계약년월,계약일,시군구,본번,부번,단지명,전월세구분,전용면적(㎡),보증금(만원),월세(만원),층,건축년도
201,201707,29,세종특별자치시 고운동,1393,0,가락마을15단지(중흥파크뷰),월세,59.9917,1000,40,3,2015
202,201708,4,세종특별자치시 고운동,1393,0,가락마을15단지(중흥파크뷰),전세,73.9816,12000,0,16,2015
203,201708,10,세종특별자치시 고운동,1393,0,가락마을15단지(중흥파크뷰),전세,73.9816,13000,0,9,2015
204,201708,12,세종특별자치시 고운동,1393,0,가락마을15단지(중흥파크뷰),전세,73.9816,13000,0,9,2015
205,201708,14,세종특별자치시 고운동,1393,0,가락마을15단지(중흥파크뷰),전세,84.9894,15000,0,14,2015
...,...,...,...,...,...,...,...,...,...,...,...,...
38890,202011,21,세종특별자치시 해밀동,6402,1,해밀마을 2단지,월세,102.8300,10000,100,5,2020
38891,202012,8,세종특별자치시 해밀동,6402,1,해밀마을 2단지,월세,102.5300,10000,95,14,2020
38892,202012,11,세종특별자치시 해밀동,6402,1,해밀마을 2단지,전세,84.9500,30000,0,18,2020
38893,202012,12,세종특별자치시 해밀동,6402,1,해밀마을 2단지,전세,84.9500,34000,0,18,2020
38894,202012,13,세종특별자치시 해밀동,6402,1,해밀마을 2단지,월세,84.9500,8000,85,16,2020

In [25]:
#5) 건축년도 컬럼 중복 제거 결과 출력  
df.건축년도.drop_duplicates().sort_values()

15189    1980
33640    1988
6551     1989
6538     1991
4184     1992
4186     1994
6564     1996
6535     1997
6936     1998
6839     1999
1898     2000
6480     2001
4180     2002
6563     2003
6823     2006
1973     2007
6880     2008
8404     2011
2826     2012
1998     2013
473      2014
0        2015
91       2016
2019     2017
2036     2018
2039     2019
19801    2020
Name: 건축년도, dtype: int64